apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-green-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
      version: green
  template:
    metadata:
      labels:
        app: django-app
        version: green
    spec:
      containers:
        - name: django-container
          image: django-app:green
          ports:
            - containerPort: 8000
